"""Pydantic models for patient data and AI match results."""
from pydantic import BaseModel, Field
from typing import Any, Dict, List, Literal, Optional


class PatientData(BaseModel):
    age: int = Field(..., description="Patient age in years")
    sex: Literal["male", "female", "other"] = Field(..., description="Biological sex")
    diagnoses: List[str] = Field(default_factory=list, description="Active diagnoses / ICD labels")
    biomarkers: Dict[str, Any] = Field(
        default_factory=dict,
        description="Lab values and molecular markers, e.g. {'EGFR': 'exon19del', 'eGFR': 45}",
    )
    medications: List[str] = Field(default_factory=list, description="Current medications")
    history: List[str] = Field(
        default_factory=list,
        description="Relevant past medical history items",
    )
    ecog_ps: Optional[int] = Field(None, description="ECOG Performance Status (0-5)")
    prior_therapies: List[str] = Field(
        default_factory=list, description="Prior treatment lines"
    )
    notes: Optional[str] = Field(None, description="Free-text clinical notes")


class CriterionVerdict(BaseModel):
    criterion_id: str = Field(..., description="e.g. INC-1, EXC-3")
    criterion_text: str
    verdict: Literal["MET", "NOT_MET", "UNCERTAIN"]
    reasoning: str
    patient_evidence: str = Field(
        ..., description="Which patient field/value was used to reach the verdict"
    )


class MatchResult(BaseModel):
    nct_id: str
    overall_eligibility: Literal["ELIGIBLE", "INELIGIBLE", "UNCERTAIN"]
    confidence: Literal["HIGH", "MEDIUM", "LOW"]
    summary: str
    criteria_verdicts: List[CriterionVerdict] = Field(default_factory=list)
    disqualifying_criteria: List[str] = Field(
        default_factory=list,
        description="IDs of criteria that definitively disqualify the patient",
    )
    raw_reasoning: str = Field(..., description="Full chain-of-thought returned by K2 Pass 1")
    # Pass 2 — Devil's Advocate Safety Audit (None if Pass 2 failed or was skipped)
    audit_verdict: Optional[str] = Field(None, description="CONFLICT_FOUND | HIGH_INTEGRITY_MATCH")
    audit_criterion: Optional[str] = Field(None, description="Criterion challenged by the auditor")
    audit_challenge: Optional[str] = Field(None, description="Devil's advocate argument text")
    audit_confidence: Optional[str] = Field(None, description="HIGH | MEDIUM | LOW")
    audit_raw: Optional[str] = Field(None, description="Raw output from Pass 2 (Skeptical Auditor)")


class MatchRequest(BaseModel):
    nct_id: str = Field(..., description="NCT ID of the trial to match against")
    patient: PatientData


_DISCLAIMER = (
    "This output is an automated eligibility pre-screen generated by an AI model. "
    "It does not constitute medical advice, a clinical diagnosis, or a treatment recommendation. "
    "All eligibility decisions must be reviewed and confirmed by a qualified investigator "
    "or clinical research coordinator before any patient action is taken."
)


class MatchResponse(BaseModel):
    nct_id: str
    trial_title: str
    eligibility_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Numeric score 0.0–1.0: fraction of criteria met, zeroed on any disqualifying exclusion",
    )
    eligibility_label: Literal["ELIGIBLE", "INELIGIBLE", "UNCERTAIN"]
    confidence: Literal["HIGH", "MEDIUM", "LOW"]
    summary: str
    reasoning_chain: List[CriterionVerdict] = Field(
        ..., description="Per-criterion audit produced by K2"
    )
    disqualifying_criteria: List[str]
    raw_reasoning: str
    audit_verdict: Optional[str] = None
    audit_criterion: Optional[str] = None
    audit_challenge: Optional[str] = None
    audit_confidence: Optional[str] = None
    audit_raw: Optional[str] = None
    disclaimer: str = Field(default=_DISCLAIMER, description="Regulatory disclaimer — not medical advice")
